networks:
  default:
    name: logion-test
    external: true

services:
# ----------------------------------------- Logion node 1 --------------------------------------------------------------
  private-database1:
    image: logionnetwork/logion-postgres:${PG_TAG:-latest}
    environment:
      - POSTGRES_PASSWORD=secret
  backend1:
    image: logionnetwork/logion-backend:${BACKEND_TAG:-latest}
    environment:
      - JWT_SECRET=c12b6d18942f5ee8528c8e2baf4e147b5c5c18710926ea492d09cbd9f6c9f82a
      - JWT_ISSUER=12D3KooWBmAwcd4PJNJvfV89HwE48nwkRmAgo8Vy3uQEyNNHBox2
      - TYPEORM_HOST=private-database1
      - WS_PROVIDER_URL=ws://$RPC_WS
      - OWNER=5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
      - DIRECTORY_URL=http://directory:8080
      - SMTP_ENABLED=false
      - IPFS_CLUSTER_HOST=/dns4/ipfs-cluster1/tcp/9094
      - IPFS_HOST=/dns4/ipfs1/tcp/5001
      - IPFS_MIN_REPLICA=1
      - IPFS_MAX_REPLICA=2
      - ENC_PASSWORD=test
    depends_on:
      - private-database1
      - ipfs-cluster1
  frontend1:
    image: logionnetwork/logion-frontend:${FRONTEND_TAG:-latest}
    ports:
      - 127.0.0.1:8080:80
    volumes:
    - ./front_config.js:/usr/share/nginx/html/config.js
    - ./front_web1.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend1
    environment:
      - CERTBOT_EMAIL=user1@invalid.domain
      - BACKEND_HOST_PORT=backend1:8080
      - NODE_HOST_PORT=$RPC_WS
  ipfs1:
    image: ipfs/go-ipfs:v0.12.0
    ports:
      - 127.0.0.1:5001:5001
    volumes:
      - ./config/ipfs1/config:/data/ipfs/config:ro
      - ./config/ipfs1/datastore_spec:/data/ipfs/datastore_spec:ro
      - ./config/ipfs1/swarm.key:/data/ipfs/swarm.key:ro
      - ./config/ipfs1/version:/data/ipfs/version:ro
  ipfs-cluster1:
    image: ipfs/ipfs-cluster:v0.14.5
    depends_on:
      - ipfs1
    ports:
      - 127.0.0.1:9094:9094
    volumes:
      - ./config/ipfs-cluster1/identity.json:/data/ipfs-cluster/identity.json:ro
      - ./config/ipfs-cluster1/service.json:/data/ipfs-cluster/service.json:ro
# ----------------------------------------- Logion directory --------------------------------------------------------------
  directory-database:
    image: postgres:12
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
  directory:
    image: logionnetwork/logion-directory:${DIRECTORY_TAG:-latest}
    ports:
      - 127.0.0.1:8090:8080
    environment:
      - JWT_SECRET=c12b6d18942f5ee8528c8e2baf4e147b5c5c18710926ea492d09cbd9f6c9f82a
      - JWT_ISSUER=12D3KooWBmAwcd4PJNJvfV89HwE48nwkRmAgo8Vy3uQEyNNHBox2
      - WS_PROVIDER_URL=ws://$RPC_WS
      - TYPEORM_HOST=directory-database
    depends_on:
      - directory-database
